version: "3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./app:/app
    tty: true
    command:
      - bash
      - -c
      - | 
        [ -f ~/.exec-once ] || {
          apt-get update
          apt-get install poppler-utils wv unrtf tidy -y
          go mod init shakyou-api;
          go mod tidy &&
          touch ~/.exec-once
        }
        swag init
        air